name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - run: yarn
      - run: npm run format:check
      - run: npm run typescript:check
      - run: npm test
      - run: npx codecov
